describe('Signup on the trymima app', () => {
  it('Can sign up successfully without a referral code', () => {
    cy.visit('/')
    cy.get('button').contains('Sign up').should('be.visible').and('exist').click()
    cy.get('.Login_logintext__center__DbD-L>h3').should('contain.text', 'Sign Up')
    cy.get('input#fullname').should('exist').type('Ireti Ayeni')
    cy.get('input#businessname').should('exist').type('Chayil')
    cy.get('input#businessemail').should('exist').type('iretiayeni03@gmail.com')
    cy.get('input#businessphonenumber').should('exist').type('08012345670')
    cy.get('input#businessRegNum').should('exist').type('08012345670')
    cy.get('button').contains('Next').should('be.visible').and('exist').click()   
    cy.get('input#website').should('exist').type('trymima.com')
    cy.get('input#instagramHandle').should('exist').type('joyful')
    cy.get('input#twitterHandle').should('exist').type('JOY')
    cy.get('.sc-cPiKLX.iafYdr').click()
    cy.get('.MimaDropdown_select__options__xLi7K').contains('Instagram').click()
    cy.get('input#password').should('exist').type('Testpassword@1')
    cy.get('button').contains('Sign Up').should('be.visible').and('exist').click()
  })
})